info:
  description: Модель данных MarketPlace
  title: Сервис "MarketPlace"
  version: 1.0.0
paths:
  /api:
    post:
      consumes:
        - application/json
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/Customer'
      produces:
        - application/json
      responses:
        '200':
          description: Запрос обработан успешно
          schema:
            $ref: '#/definitions/Customer'
        '400':
          description: Неправильный запрос
          schema:
            $ref: '#/definitions/Customer'
        '500':
          description: Произошла техническая ошибка
          schema:
            $ref: '#/definitions/Customer'

swagger: '2.0'
x-components: { }
definitions:
  Customer:
    additionalProperties: false
    properties:
      userId:
        type: string
        format: uuid
      userName:
        type: string
        maxLength: 30
      userPassword:
        type: string
        maxLength: 20
      email:
        type: string
        maxLength: 30
    required:
      - userId
      - userName
      - userPassword
    type: object
  Card:
    additionalProperties: false
    properties:
      cardId:
        type: integer
        format: int64
      userId:
        type: string
        format: uuid
      cardNumber:
        type: string
        pattern: '^[0-9]{16}$'
      cardAmount:
        type: number
        format: double
    required:
      - cardId
      - userId
      - cardNumber
      - cardAmount
    type: object
  Good:
    additionalProperties: false
    properties:
      goodId:
        type: integer
        format: int64
      goodName:
        type: string
        maxLength: 30
      goodPrice:
        type: number
        format: float
    required:
      - goodId
      - goodName
      - goodPrice
    type: object
  IssuingPoint:
    additionalProperties: false
    properties:
      issuingPointId:
        type: integer
        format: int64
      address:
        type: string
        maxLength: 50
      owner:
        type: string
        maxLength: 30
      work_schedule:
        type: string
        maxLength: 20
    required:
      - issuingPointId
      - address
    type: object
  Order:
    additionalProperties: false
    properties:
      orderId:
        type: integer
        format: int64
      cardId:
        type: integer
        format: int64
      orderAmount:
        type: number
        format: double
      status:
        type: string
        enum: ['PAID','DELIVERING','WAIT_ISSUING','ISSUED','DENIED']
      purchaseTime:
        type: string
        format: date-time
      deliveryTime:
        type: string
        format: date-time
      issuingTime:
        type: string
        format: date-time
    required:
      - issuingPointId
      - address
    type: object
