@startuml
class customer_table {
.. columns ..
{field} -user_id uuid PRIMARY KEY UNIQUE NOT NULL,
{field} +user_name varchar(50) NOT NULL,
{field} +user_password varchar(20) NOT NULL,
{field} +email varchar(30) UNIQUE
}

class order_table {
.. columns ..
{field} -order_id uuid PRIMARY KEY NOT NULL,
{field} #user_id uuid UNIQUE NOT NULL,
{field} +order_amount double NOT NULL
}

class good_table {
.. columns ..
{field} -good_id uuid PRIMARY KEY NOT NULL,
{field} +good_name varchar(50) NOT NULL,
{field} +good_price double NOT NULL
}

class order_history_table {
.. columns ..
{field} -id bigint PRIMARY KEY NOT NULL,
{field} +operation varchar(20) NOT NULL,
{field} +time TIMESTAMP WITH TIME ZONE NOT NULL,
{field} -order_id uuid NOT NULL,
}

class order_details_table {
.. columns ..
{field} -detail_id uuid PRIMARY KEY NOT NULL,
{field} #order_id uuid NOT NULL,
{field} #good_id uuid NOT NULL,
{field} +goods_count int NOT NULL
}


order_table "many" --* "1 " customer_table : by user_id
order_table "many" *--* "many" good_table : by order_details table
@enduml